version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: classified_user
      POSTGRES_PASSWORD: classified_pass
      POSTGRES_DB: classified_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=classified_db
      - DB_USER=classified_user
      - DB_PASS=classified_pass
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local 